apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ollama-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: simaoarrais/ollama-chatbot
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: app-env
