apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: chatbot
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
      nodePort: 30105
  type: NodePort
